=== alieron/etoile/public/data/constellations.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Constellation",
  "type": "object",
  "required": [
    "id",
    "name",
    "gen",
    "meaning",
    "rank",
    "focus",
    "label",
    "bound",
    "lines",
    "bright"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "gen": {
      "type": "string"
    },
    "meaning": {
      "type": "string"
    },
    "rank": {
      "type": "integer"
    },
    "focus": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "number"
      }
    },
    "label": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "number"
      }
    },
    "bound": {
      "type": [
        "array",
        "null"
      ]
    },
    "lines": {
      "type": [
        "array",
        "null"
      ]
    },
    "bright": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "additionalProperties": false
}

=== alieron/etoile/public/data/constellations/mon.json
{
  "id": "Mon",
  "name": "Monoceros",
  "gen": "Monocerotis",
  "meaning": "Unicorn",
  "rank": 1,
  "focus": [
    105,
    0,
    73
  ],
  "label": [
    114.75,
    -6
  ],
  "bound": [
    [
      [
        95.2257,
        -0.0537
      ],
      [
        95.348,
        9.9455
      ],
      [
        96.3477,
        9.9334
      ],
      [
        96.3728,
        11.9333
      ],
      [
        105.7428,
        11.8213
      ],
      [
        105.7185,
        9.8215
      ],
      [
        106.7179,
        9.8098
      ],
      [
        106.6643,
        5.3101
      ],
      [
        106.9143,
        5.3072
      ],
      [
        106.8674,
        1.3074
      ],
      [
        109.6169,
        1.2756
      ],
      [
        109.5997,
        -0.2243
      ],
      [
        122.849,
        -0.3694
      ],
      [
        122.7342,
        -11.3688
      ],
      [
        111.9734,
        -11.2521
      ],
      [
        93.2156,
        -11.0302
      ],
      [
        88.9658,
        -10.9785
      ],
      [
        89.0524,
        -3.9791
      ],
      [
        95.1771,
        -4.0534
      ]
    ]
  ],
  "lines": [
    [
      "s_monocerotis",
      "13_monocerotis",
      "epsilon_monocerotis_a",
      "epsilon_monocerotis_a",
      "18_monocerotis",
      "13_monocerotis",
      "18_monocerotis",
      "delta_monocerotis",
      "beta_1_monocerotis",
      "gamma_monocerotis",
      "beta_1_monocerotis",
      "delta_monocerotis",
      "zeta_monocerotis",
      "alpha_monocerotis"
    ]
  ],
  "bright": "beta_1_monocerotis"
}

=== alieron/etoile/public/data/constellations/hyi.json
{
  "id": "Hyi",
  "name": "Hydrus",
  "gen": "Hydri",
  "meaning": "Male Water Snake",
  "rank": 2,
  "focus": [
    35.1637,
    -69.9564,
    102
  ],
  "label": [
    34.5,
    -72
  ],
  "bound": [
    [
      [
        68.794,
        -67.2479
      ],
      [
        68.5815,
        -69.7467
      ],
      [
        67.9575,
        -74.7432
      ],
      [
        52.0758,
        -74.5741
      ],
      [
        50.0917,
        -82.0645
      ],
      [
        1.5334,
        -81.804
      ],
      [
        1.5663,
        -74.304
      ],
      [
        12.3324,
        -74.3186
      ],
      [
        12.2954,
        -75.3185
      ],
      [
        20.6541,
        -75.3472
      ],
      [
        21.2062,
        -57.8484
      ],
      [
        33.4894,
        -57.9162
      ],
      [
        33.2024,
        -66.9152
      ],
      [
        48.3627,
        -67.0358
      ]
    ]
  ],
  "lines": [
    [
      "beta_hydri",
      "gamma_hydri",
      "delta_hydri",
      "alpha_hydri",
      "beta_hydri"
    ]
  ],
  "bright": "beta_hydri"
}
