=== alieron/etoile/public/data/stars.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Star",
  "type": "object",
  "required": [
    "id",
    "name",
    "rank",
    "ra",
    "dec",
    "dist",
    "otype",
    "spect",
    "cat"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "proper": {
      "type": "string"
    },
    "rank": {
      "type": "integer",
      "minimum": 0,
      "maximum": 5
    },
    "by": {
      "type": "string"
    },
    "by_greek": {
      "type": "string"
    },
    "by_con": {
      "type": "string"
    },
    "by_comp": {
      "type": "string"
    },
    "v": {
      "type": "string"
    },
    "v_con": {
      "type": "string"
    },
    "v_comp": {
      "type": "string"
    },
    "fl": {
      "type": "integer"
    },
    "fl_con": {
      "type": "string"
    },
    "fl_comp": {
      "type": "string"
    },
    "ra": {
      "type": "number"
    },
    "dec": {
      "type": "number"
    },
    "dist": {
      "type": "number"
    },
    "otype": {
      "type": [
        "string",
        "null"
      ]
    },
    "spect": {
      "type": [
        "string",
        "null"
      ]
    },
    "cat": {
      "type": "integer",
      "minimum": 0
    }
  },
  "dependentRequired": {
    "by": [
      "by_greek",
      "by_con"
    ],
    "by_greek": [
      "by",
      "by_con"
    ],
    "by_con": [
      "by",
      "by_greek"
    ],
    "v": [
      "v_con"
    ],
    "v_con": [
      "v"
    ],
    "fl": [
      "fl_con"
    ],
    "fl_con": [
      "fl"
    ]
  },
  "additionalProperties": false
}

=== alieron/etoile/public/data/stars/d_1_virginis_b.json
{
  "id": "d_1_virginis_b",
  "name": "d 1 Virginis B",
  "rank": 4,
  "ra": 190.48871521692996,
  "dec": 6.807516914420001,
  "dist": 81.02,
  "otype": "PM*",
  "spect": "",
  "cat": 0,
  "by": "d01",
  "by_greek": "d¹",
  "by_con": "Vir",
  "by_comp": "B",
  "fl": 31,
  "fl_con": "Vir",
  "fl_comp": "B"
}

=== alieron/etoile/public/data/stars/epsilon_canis_majoris_b.json
{
  "id": "epsilon_canis_majoris_b",
  "name": "Epsilon Canis Majoris B",
  "rank": 4,
  "ra": 104.65722781236208,
  "dec": -28.974127640268343,
  "dist": 131.304,
  "otype": "*",
  "spect": "",
  "cat": 0,
  "by": "eps",
  "by_greek": "ε",
  "by_con": "CMa",
  "by_comp": "B",
  "fl": 21,
  "fl_con": "CMa",
  "fl_comp": "B"
}

=== alieron/etoile/public/data/stars/n_1_orionis_b.json
{
  "id": "n_1_orionis_b",
  "name": "n 1 Orionis B",
  "rank": 4,
  "ra": 82.81079290682,
  "dec": 3.2926015140700002,
  "dist": 333.589,
  "otype": "*",
  "spect": "",
  "cat": 0,
  "by": "n01",
  "by_greek": "n¹",
  "by_con": "Ori",
  "by_comp": "B",
  "fl": 33,
  "fl_con": "Ori",
  "fl_comp": "B"
}

=== alieron/etoile/public/data/stars/eta_coronae_borealis_a.json
{
  "id": "eta_coronae_borealis_a",
  "name": "Eta Coronae Borealis A",
  "rank": 4,
  "ra": 230.80127230988052,
  "dec": 30.287825023864578,
  "dist": 17.863678635,
  "otype": "*",
  "spect": "G2V+G2V",
  "cat": 5,
  "by": "eta",
  "by_greek": "η",
  "by_con": "CrB",
  "by_comp": "A",
  "fl": 2,
  "fl_con": "CrB",
  "fl_comp": "A"
}

=== alieron/etoile/public/data/stars/beta_geminorum.json
{
  "id": "beta_geminorum",
  "name": "Beta Geminorum",
  "rank": 2,
  "ra": 116.32895777437875,
  "dec": 28.02619889009357,
  "dist": 10.3584,
  "otype": "PM*",
  "spect": "K0IIIb",
  "cat": 15,
  "proper": "Pollux",
  "by": "bet",
  "by_greek": "β",
  "by_con": "Gem",
  "fl": 78,
  "fl_con": "Gem"
}

=== alieron/etoile/public/data/stars/epsilon_1_lyrae_a.json
{
  "id": "epsilon_1_lyrae_a",
  "name": "Epsilon 1 Lyrae A",
  "rank": 3,
  "ra": 281.0847745484784,
  "dec": 39.67012591180029,
  "dist": 49.776497760000005,
  "otype": "PM*",
  "spect": "A3V+F0V",
  "cat": 7,
  "by": "eps01",
  "by_greek": "ε¹",
  "by_con": "Lyr",
  "by_comp": "A",
  "fl": 4,
  "fl_con": "Lyr",
  "fl_comp": "A"
}

=== alieron/etoile/public/data/stars/beta_capricorni.json
{
  "id": "beta_capricorni",
  "name": "Beta Capricorni",
  "rank": 2,
  "ra": 305.25277749238,
  "dec": -14.78140760208,
  "dist": 100.2004,
  "otype": "SB*",
  "spect": "G9II:+B8p:Si:",
  "cat": 13,
  "proper": "Dabih",
  "by": "bet",
  "by_greek": "β",
  "by_con": "Cap",
  "fl": 9,
  "fl_con": "Cap"
}

=== alieron/etoile/public/data/stars/gamma_capricorni.json
{
  "id": "gamma_capricorni",
  "name": "Gamma Capricorni",
  "rank": 2,
  "ra": 325.0226892543413,
  "dec": -16.66237119824361,
  "dist": 48.1464,
  "otype": "a2*",
  "spect": "kF0hF1VmF2",
  "cat": 20,
  "proper": "Nashira",
  "by": "gam",
  "by_greek": "γ",
  "by_con": "Cap",
  "fl": 40,
  "fl_con": "Cap"
}
