=== alieron/etoile/public/data/stars.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Star",
  "type": "object",
  "required": [
    "id",
    "name",
    "rank",
    "ra",
    "dec",
    "dist",
    "otype",
    "spect",
    "cat"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "proper": {
      "type": "string"
    },
    "rank": {
      "type": "integer",
      "minimum": 0,
      "maximum": 5
    },
    "by": {
      "type": "string"
    },
    "by_greek": {
      "type": "string"
    },
    "by_con": {
      "type": "string"
    },
    "by_comp": {
      "type": "string"
    },
    "v": {
      "type": "string"
    },
    "v_con": {
      "type": "string"
    },
    "v_comp": {
      "type": "string"
    },
    "fl": {
      "type": "integer"
    },
    "fl_con": {
      "type": "string"
    },
    "fl_comp": {
      "type": "string"
    },
    "ra": {
      "type": "number"
    },
    "dec": {
      "type": "number"
    },
    "dist": {
      "type": "number"
    },
    "otype": {
      "type": [
        "string",
        "null"
      ]
    },
    "spect": {
      "type": [
        "string",
        "null"
      ]
    },
    "cat": {
      "type": "integer",
      "minimum": 0
    }
  },
  "dependentRequired": {
    "by": [
      "by_greek",
      "by_con"
    ],
    "by_greek": [
      "by",
      "by_con"
    ],
    "by_con": [
      "by",
      "by_greek"
    ],
    "v": [
      "v_con"
    ],
    "v_con": [
      "v"
    ],
    "fl": [
      "fl_con"
    ],
    "fl_con": [
      "fl"
    ]
  },
  "additionalProperties": false
}

=== alieron/etoile/public/data/stars/alpha_ursae_minoris.json
{
  "id": "alpha_ursae_minoris",
  "name": "Alpha Ursae Minoris",
  "rank": 2,
  "ra": 37.954560670189856,
  "dec": 89.26410896994187,
  "dist": 132.626,
  "otype": "cC*",
  "spect": "F8Ib",
  "cat": 18,
  "proper": "Polaris",
  "by": "alf",
  "by_greek": "α",
  "by_con": "UMi",
  "fl": 1,
  "fl_con": "UMi"
}

=== alieron/etoile/public/data/stars/b_1_cygni.json
{
  "id": "b_1_cygni",
  "name": "b 1 Cygni",
  "rank": 4,
  "ra": 301.5906970720503,
  "dec": 35.97246919934528,
  "dist": 23.9464,
  "otype": "RS*",
  "spect": "G8.5IVa",
  "cat": 11,
  "by": "b01",
  "by_greek": "b¹",
  "by_con": "Cyg",
  "v": "V2008",
  "v_con": "Cyg",
  "fl": 27,
  "fl_con": "Cyg"
}

=== alieron/etoile/public/data/stars/alpha_canum_venaticorum_a.json
{
  "id": "alpha_canum_venaticorum_a",
  "name": "Alpha Canum Venaticorum A",
  "rank": 2,
  "ra": 194.00693995375286,
  "dec": 38.31837643625333,
  "dist": 35.1989,
  "otype": "a2*",
  "spect": "A0VpSiEu",
  "cat": 20,
  "proper": "Cor Caroli",
  "by": "alf",
  "by_greek": "α",
  "by_con": "CVn",
  "by_comp": "A",
  "fl": 12,
  "fl_con": "CVn",
  "fl_comp": "A"
}

=== alieron/etoile/public/data/stars/omega_1_cygni.json
{
  "id": "omega_1_cygni",
  "name": "Omega 1 Cygni",
  "rank": 4,
  "ra": 307.51475394137,
  "dec": 48.95156682478001,
  "dist": 278.5515,
  "otype": "Pu*",
  "spect": "B2.5IV",
  "cat": 9,
  "by": "ome01",
  "by_greek": "ω¹",
  "by_con": "Cyg",
  "v": "V2014",
  "v_con": "Cyg",
  "fl": 45,
  "fl_con": "Cyg"
}

=== alieron/etoile/public/data/stars/nu_3_canis_majoris_b.json
{
  "id": "nu_3_canis_majoris_b",
  "name": "Nu 3 Canis Majoris B",
  "rank": 4,
  "ra": 99.47260394166668,
  "dec": -18.237188158333336,
  "dist": 129.199,
  "otype": "*",
  "spect": "",
  "cat": 0,
  "by": "nu.03",
  "by_greek": "ν³",
  "by_con": "CMa",
  "by_comp": "B",
  "fl": 8,
  "fl_con": "CMa",
  "fl_comp": "B"
}

=== alieron/etoile/public/data/stars/psi_1_draconis_a.json
{
  "id": "psi_1_draconis_a",
  "name": "Psi 1 Draconis A",
  "rank": 2,
  "ra": 265.48359320893996,
  "dec": 72.14886878277,
  "dist": 22.8363,
  "otype": "SB*",
  "spect": "F5IV-V",
  "cat": 11,
  "proper": "Dziban",
  "by": "psi01",
  "by_greek": "ψ¹",
  "by_con": "Dra",
  "by_comp": "A",
  "fl": 31,
  "fl_con": "Dra",
  "fl_comp": "A"
}

=== alieron/etoile/public/data/stars/sigma_coronae_borealis_a.json
{
  "id": "sigma_coronae_borealis_a",
  "name": "Sigma Coronae Borealis A",
  "rank": 4,
  "ra": 243.67023154593198,
  "dec": 33.85859713697483,
  "dist": 21.079510793,
  "otype": "SB*",
  "spect": "F6V+G0V",
  "cat": 6,
  "by": "sig",
  "by_greek": "σ",
  "by_con": "CrB",
  "by_comp": "A",
  "fl": 17,
  "fl_con": "CrB",
  "fl_comp": "A"
}

=== alieron/etoile/public/data/stars/eta_canis_minoris_b.json
{
  "id": "eta_canis_minoris_b",
  "name": "Eta Canis Minoris B",
  "rank": 4,
  "ra": 112.00920804598,
  "dec": 6.94302354986,
  "dist": 97.502,
  "otype": "*",
  "spect": "",
  "cat": 0,
  "by": "eta",
  "by_greek": "η",
  "by_con": "CMi",
  "by_comp": "B",
  "fl": 5,
  "fl_con": "CMi",
  "fl_comp": "B"
}
